---
- name: Install system utilities
  hosts: localhost
  connection: local
  become: yes
  vars:
    system_arch: "{{ ansible_architecture }}"
    
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install Git (from OS repo)
      apt:
        name: git
        state: present

    - name: Install ripgrep (from OS repo)
      apt:
        name: ripgrep
        state: present

    - name: Install fd-find (from OS repo) - provides fdfind command
      apt:
        name: fd-find
        state: present

    - name: Install procs (from OS repo)
      apt:
        name: procs
        state: present

    - name: Install glances (from OS repo)
      apt:
        name: glances
        state: present

    - name: Install lsd (from OS repo)
      apt:
        name: lsd
        state: present

    - name: Create symlink fd -> fdfind (if fd-find installed)
      file:
        src: /usr/bin/fdfind
        dest: /usr/local/bin/fd
        state: link
        force: yes
      when: "'fd-find' in ansible_facts.packages"

    - name: Check if witr is available in Debian repos
      command: apt-cache search ^witr$
      register: witr_search
      ignore_errors: yes
      changed_when: false

    - name: Install witr from GitHub (if not in Debian repos)
      block:
        - name: Determine architecture for witr
          set_fact:
            witr_arch: "{% if system_arch == 'x86_64' %}x86_64{% elif system_arch == 'aarch64' %}aarch64{% elif system_arch == 'armv7l' %}armv7{% else %}x86_64{% endif %}"

        - name: Get latest witr release info
          uri:
            url: "https://api.github.com/repos/pranshuparmar/witr/releases/latest"
            return_content: yes
            headers:
              Accept: "application/vnd.github.v3+json"
          register: witr_release
          until: witr_release.status == 200
          retries: 3
          delay: 2

        - name: Extract witr download URL
          set_fact:
            witr_download_url: "{{ witr_release.json.assets | selectattr('name', 'match', '.*' + witr_arch + '.*linux.*tar.gz$') | map(attribute='browser_download_url') | first }}"

        - name: Download witr
          get_url:
            url: "{{ witr_download_url }}"
            dest: "/tmp/witr.tar.gz"
            mode: '0644'

        - name: Extract witr
          unarchive:
            src: "/tmp/witr.tar.gz"
            dest: "/tmp"
            remote_src: yes
            creates: "/tmp/witr"

        - name: Install witr binary
          copy:
            src: "/tmp/witr"
            dest: "/usr/local/bin/witr"
            mode: '0755'
            remote_src: yes

        - name: Clean up temp files
          file:
            path: "{{ item }}"
            state: absent
          loop:
            - "/tmp/witr.tar.gz"
            - "/tmp/witr"
      when: witr_search.stdout_lines | length == 0

    - name: Verify installations
      command: "{{ item }} --version"
      register: version_checks
      ignore_errors: yes
      changed_when: false
      loop:
        - git
        - rg
        - fdfind
        - procs
        - glances
        - lsd
        - witr

    - name: Display installation results
      debug:
        msg: |
          Установка завершена:
          Git: {{ '✓' if 'git version' in version_checks.results[0].stdout else '✗' }}
          ripgrep: {{ '✓' if 'ripgrep' in version_checks.results[1].stdout else '✗' }}
          fd: {{ '✓' if 'fd' in version_checks.results[2].stdout or 'fdfind' in version_checks.results[2].stdout else '✗' }}
          procs: {{ '✓' if 'procs' in version_checks.results[3].stdout else '✗' }}
          glances: {{ '✓' if 'glances' in version_checks.results[4].stdout else '✗' }}
          lsd: {{ '✓' if 'lsd' in version_checks.results[5].stdout else '✗' }}
          witr: {{ '✓' if version_checks.results[6].rc == 0 else '✗' }}